version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci_project
      MYSQL_USER: ci_project
      MYSQL_PASSWORD: ci_project_pass
    ports:
      - 3306:3306
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80

  app:
    build:   .
    command: npm start
    volumes:
      - .:/src
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - db
